const config = {
  botName: 'NA MD Bot',
  developer: 'Nisha Aslam',
  ownerName: 'Nisha Aslam',
  brand: 'NA MD Bot',
  version: '1.0.0',
  ownerNumber: ['923316041183'],
  superOwner: ['923346741532', '923334070793'],
  channelLink: 'https://whatsapp.com/channel/0029Vb8FrxpKwqSLNkh4FZ3U',
  newsletterJid: '',
  newsletterName: 'NA MD Bot',
  prefix: ['.'],
  altPrefixes: [],
  owners: [],
  botMode: 'public',
  sessionDir: './session',
  databaseDir: './database',
  logsDir: './logs',
  tempDir: './temp',
  mediaDir: './media',
  maxFileSize: 50 * 1024 * 1024,
  autoRead: true,
  autoTyping: true,
  antiSpam: true,
  spamInterval: 5,
  spamMax: 5,
  cooldown: 3,
  xpPerMessage: 5,
  xpPerCommand: 10,
  startingBalance: 1000,
  dailyAmount: 500,
  maxDailyStreak: 7,
  maintenanceMode: false,
  maintenanceMsg: '🔧 Bot is under maintenance. Please wait...',
  welcomeMessage: true,
  timezone: 'Asia/Karachi',
  language: 'en',
  autoStatusView: true,
  autoStatusReact: true,
  autoStatus: false,
  statusEmoji: '❤️',
  apiKeys: {
    openweather: process.env.OPENWEATHER_API_KEY || '',
    omdb: process.env.OMDB_API_KEY || '',
  },
};

export default config;
